:construction_worker: move status checks to workflow with correct permissions even for fork PRs

diff --git a/.github/actions/run-hurl-testsuite/action.yml b/.github/actions/run-hurl-testsuite/action.yml
--- a/.github/actions/run-hurl-testsuite/action.yml
+++ b/.github/actions/run-hurl-testsuite/action.yml
@@ -9,9 +9,6 @@ inputs:
   pr:
     description: Pull Request ID
     required: false
-  ghtoken:
-    description: GitHub Token
-    required: true
   testsuite:
     description: Test suite to run (api, web, k8s)
     required: true
@@ -30,44 +27,38 @@ runs:
         FLOWG_TEST_SUITES: ${{ inputs.testsuite }}
         FLOWG_TEST_DOCKER_IMAGE_NAME: ghcr.io/link-society/flowg/ci-artifacts/docker:${{ inputs.ref }}-linux-amd64
 
-    - name: report-success@status
-      uses: guibranco/github-status-action-v2@77639353504055053524efa7a3719aaf0b731ce9 # v1.2.4
+    - name: write@metadata
+      if: ${{ !cancelled() }}
+      shell: bash
+      env:
+        META_SHA: ${{ inputs.ref }}
+        META_PR: ${{ inputs.pr }}
+        META_CHECKNAME: ${{ inputs.checkname }}
+      run: |
+        mkdir -p ./tests/reports/${{ inputs.testsuite }}
+        echo -n "${META_SHA}" > ./tests/reports/${{ inputs.testsuite }}/meta.sha
+        echo -n "${META_PR}" > ./tests/reports/${{ inputs.testsuite }}/meta.pr
+        echo -n "${META_CHECKNAME}" > ./tests/reports/${{ inputs.testsuite }}/meta.checkname
+
+    - name: write-success@outcome
       if: ${{ success() }}
-      with:
-        authToken: ${{ inputs.ghtoken }}
-        context: ${{ inputs.checkname }}
-        description: 'Passed'
-        state: 'success'
-        sha: ${{ inputs.ref }}
+      shell: bash
+      run: echo -n "success" > ./tests/reports/${{ inputs.testsuite }}/meta.outcome
 
-    - name: report-failure@status
-      uses: guibranco/github-status-action-v2@77639353504055053524efa7a3719aaf0b731ce9 # v1.2.4
+    - name: write-failure@outcome
       if: ${{ failure() }}
-      with:
-        authToken: ${{ inputs.ghtoken }}
-        context: ${{ inputs.checkname }}
-        description: 'Failure'
-        state: 'failure'
-        sha: ${{ inputs.ref }}
+      shell: bash
+      run: echo -n "failure" > ./tests/reports/${{ inputs.testsuite }}/meta.outcome
 
-    - name: upload-logs@artifact
-      if: ${{ failure() }}
+    - name: upload@artifact
+      if: ${{ !cancelled() }}
       uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
       with:
-        name: ${{ inputs.testsuite }}-e2e-reports
+        name: e2e-report-${{ inputs.testsuite }}
         path: "./tests/reports/${{ inputs.testsuite }}/"
         retention-days: 1
 
-    - name: report@test
-      uses: mikepenz/action-junit-report@d9f48fc87bc235f7e214acf696ca5abc0a986f16 # v6.4.2
-      if: ${{ success() || failure() }}
-      with:
-        report_paths: "./tests/reports/${{ inputs.testsuite }}/junit.xml"
-        include_passed: true
-        check_name: "${{ inputs.checkname }}"
-        job_summary: true
-        comment: ${{ inputs.pr != '' }}
-        updateComment: ${{ inputs.pr != '' }}
-        fail_on_failure: true
-        commit: ${{ inputs.ref }}
-        pr_id: ${{ inputs.pr }}
+    - name: report@fail
+      if: ${{ failure() }}
+      shell: bash
+      run: exit 1
